# Generated by Django 5.2 on 2026-02-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Admin must approve before product is visible to customers",
            ),
        ),
    ]
