# Generated by Django 5.2 on 2026-02-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_add_product_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Product discount %",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Override vendor shipping fee",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tax_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Override vendor tax %",
                max_digits=5,
                null=True,
            ),
        ),
    ]
