# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_add_product_tax_discount_shipping"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, help_text="Product brand; falls back to vendor store name if empty", max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="about_this_item",
            field=models.TextField(blank=True, help_text='Bullet points for "About this item" (one per line)'),
        ),
        migrations.AddField(
            model_name="product",
            name="technical_specs",
            field=models.JSONField(blank=True, default=dict, help_text='Key-value technical specs e.g. {"Size": "24 Inch", "Resolution": "1080p"}'),
        ),
    ]
