# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_add_product_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, help_text="e.g. S,M,L or 10,12,14 or one size", max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="dimension",
            field=models.CharField(blank=True, help_text="e.g. 24 x 18 x 6 inches", max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.CharField(blank=True, help_text="e.g. 2.5 kg or 5 lbs", max_length=80),
        ),
    ]
