# Generated by Django 5.2 on 2026-02-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="default_discount_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Default discount % for products",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="default_shipping_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="Default shipping/delivery fee",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="tax_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="Tax percentage to charge",
                max_digits=5,
            ),
        ),
    ]
